version: '3.8'

services:
  mysqldb:
    image: mysql:8.2.0
    container_name: legaliga_db
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_DATABASE
    ports:
      - $DB_LOCAL_PORT:$DB_PORT
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    container_name: legaliga_back
    build: ./
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $LOCAL_PORT:$PORT
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_DATABASE
      - DB_PORT=$DB_PORT
    stdin_open: true
    tty: true

volumes: 
  db: